name: sysfoo-ci-pipeline
on:
  push:
    branches:
    - 'master'
jobs:
  sysfoo-ci-jobs:
    runs-on: ubuntu-latest
    steps:
      - name: Hello world
        run: echo "welcome"
      - name: Code Checkout
        uses: actions/checkout@v6
      - name: Test
        run: mvn test
      - name: clean package
        run: mvn clean
      - name: Install Package
        run: mvn package
      - name: view the file
        run: ls -lrt
      - name: upload artifact
        uses: actions/upload-artifact@v4
        with:
         name: sysfoo
         path: target/**.war
